import React, { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';
import { FileText, Download, Link as LinkIcon, Plus, CheckCircle2, Clock, Check } from 'lucide-react';

/* ─── Report Row Component ─── */
const ReportRow = ({ report }) => {
  const [copied, setCopied] = useState(false);
  const [downloading, setDownloading] = useState(false);

  const handleCopyLink = () => {
    const portalUrl = `${window.location.origin}/audit/${report.access_token}`;
    navigator.clipboard.writeText(portalUrl);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    setDownloading(true);
    // Create a dummy CSV file to simulate the export download
    const dummyData = `Audit Report: ${report.name}\nFramework: ${report.framework}\nGenerated By: ${report.generated_by}\nPeriod: ${report.from_date} to ${report.to_date}\n\nControl Code,Status,Evidence\nCC6.1,Compliant,s3://evidence/log_42.json\nCC6.4,Compliant,s3://evidence/mfa_config.png`;
    const blob = new Blob([dummyData], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    
    const a = document.createElement('a');
    a.href = url;
    a.download = `auditchain_export_${report.access_token}.csv`;
    a.click();
    
    URL.revokeObjectURL(url);
    setTimeout(() => setDownloading(false), 500);
  };

  return (
    <tr className="hover:bg-[rgba(255,255,255,0.02)] transition-colors">
      <td className="py-4 px-4">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-[rgba(16,185,129,0.1)] border border-[rgba(16,185,129,0.2)] flex items-center justify-center text-emerald-500">
            <FileText size={16} />
          </div>
          <div className="text-[13px] font-medium text-white">{report.name}</div>
        </div>
      </td>
      <td className="py-4 px-4">
        <span className="text-[11px] font-semibold px-2 py-0.5 rounded-md bg-[#16161F] text-[#a1a1aa] border border-[rgba(255,255,255,0.06)] uppercase">
          {report.framework}
        </span>
      </td>
      <td className="py-4 px-4 text-[12px] text-[#71717a] tabular-nums">
        {new Date(report.from_date).toLocaleDateString()} - {new Date(report.to_date).toLocaleDateString()}
      </td>
      <td className="py-4 px-4 text-[12px] text-[#71717a]">{report.generated_by}</td>
      <td className="py-4 px-4">
        <div className="flex items-center gap-1.5 text-[11px] font-semibold text-emerald-400 bg-[rgba(16,185,129,0.1)] border border-[rgba(16,185,129,0.15)] px-2 py-0.5 rounded-md w-fit">
          <CheckCircle2 size={12} /> Ready
        </div>
      </td>
      <td className="py-4 px-4">
        <div className="flex items-center gap-2">
          <button 
            onClick={handleCopyLink}
            className={`h-7 px-3 rounded-lg border text-[11px] font-medium transition-all flex items-center gap-1.5 ${
              copied 
                ? 'bg-[rgba(16,185,129,0.1)] border-[rgba(16,185,129,0.2)] text-emerald-400' 
                : 'bg-[rgba(255,255,255,0.04)] border-[rgba(255,255,255,0.06)] text-white hover:bg-[rgba(255,255,255,0.08)]'
            }`}
          >
            {copied ? <Check size={12} /> : <LinkIcon size={12} />} 
            {copied ? 'Copied!' : 'Copy Portal Link'}
          </button>
          <button 
            onClick={handleDownload}
            disabled={downloading}
            className="h-7 w-7 flex items-center justify-center rounded-lg bg-[rgba(255,255,255,0.04)] border border-[rgba(255,255,255,0.06)] text-white hover:bg-[rgba(255,255,255,0.08)] transition-colors disabled:opacity-50"
          >
            {downloading ? <Clock size={12} className="animate-spin" /> : <Download size={12} />}
          </button>
        </div>
      </td>
    </tr>
  );
};

const Export = () => {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);

  const fetchReports = async () => {
    try {
      const { data } = await supabase
        .from('audit_exports')
        .select('*')
        .order('generated_at', { ascending: false });
      setReports(data || []);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReports();
  }, []);

  const handleGenerate = async () => {
    setGenerating(true);
    // Simulate generation delay
    setTimeout(async () => {
      try {
        const { data: { user } } = await supabase.auth.getUser();
        await supabase.from('audit_exports').insert({
          name: `SOC 2 Real-Time Snapshot - ${new Date().toLocaleDateString()}`,
          framework: 'soc2',
          from_date: new Date(new Date().setMonth(new Date().getMonth() - 1)).toISOString().split('T')[0],
          to_date: new Date().toISOString().split('T')[0],
          generated_by: user?.email || 'officer@auditchain.dev',
          access_token: `tok_${Math.random().toString(36).substring(2, 15)}`,
          control_count: 15,
          status: 'ready'
        });
        await fetchReports();
      } catch (err) {
        console.error(err);
      } finally {
        setGenerating(false);
      }
    }, 1500);
  };

  if (loading) {
    return <div className="text-white p-8">Loading reports...</div>;
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-end justify-between">
        <div>
          <h1 className="text-[24px] font-bold text-white tracking-tight">Audit Reports & Export</h1>
          <p className="text-[13px] text-[#52525B] mt-1">Generate snapshot packages for external auditors</p>
        </div>
        <button 
          onClick={handleGenerate}
          disabled={generating}
          className="h-9 px-4 rounded-lg bg-emerald-500 text-[12px] font-semibold text-white hover:bg-emerald-400 transition-all shadow-[0_0_16px_rgba(16,185,129,0.25)] flex items-center gap-2 disabled:opacity-50"
        >
          {generating ? <Clock size={14} className="animate-spin" /> : <Plus size={14} />}
          {generating ? 'Compiling Evidence...' : 'Generate New Report'}
        </button>
      </div>

      <div className="bg-[#0e0e16] rounded-xl border border-[rgba(255,255,255,0.06)] overflow-hidden">
        <table className="w-full text-left">
          <thead className="bg-[rgba(255,255,255,0.02)]">
            <tr className="border-b border-[rgba(255,255,255,0.06)]">
              {['Report Name', 'Framework', 'Period', 'Generated By', 'Status', 'Actions'].map((h) => (
                <th key={h} className="text-[10px] font-semibold text-[#3f3f46] uppercase tracking-[0.08em] py-3 px-4">{h}</th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y divide-[rgba(255,255,255,0.03)]">
            {reports.map((report) => (
              <ReportRow key={report.id} report={report} />
            ))}
            {reports.length === 0 && (
              <tr>
                <td colSpan={6} className="py-12 text-center text-[#52525B] text-[13px]">
                  No reports generated yet. Click the button above to create one.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default Export;
